-- These questions are asked in interviews.

use employees;
select * from employee;


-- Write a query to calculate the total salary generated by each department
select department , sum(salary) as total_salary
 from employee
 group by department;
 
-- Display the names of employees who have a salary above the average salary in thier department.
select first_name , department ,salary
from employee e 
where salary > (select avg(salary)
                     from employee 
                     where department = e.department     
				) ;

-- OR 
select first_name , department ,salary
from employee
 where salary > (
         select avg(salary) 
		 from employee)
 ;
 
 
-- Write a SQL query to find employees who have not had join  in the 2 years.
select first_name , date_of_joining
 from employee
 where date_of_joining < date_sub(curdate() , INTERVAL 2 year); 
 

 

 -- identify the second highest salary in each department.
SELECT  DEPARTMENT ,FIRST_NAME , SALARY 
 FROM (
	   SELECT 
              DEPARTMENT ,
              FIRST_NAME ,
              SALARY , 
			  DENSE_RANK() OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RNK
              
 FROM EMPLOYEE) AS RANKED
 WHERE RNK = 2 ;
 
-- WRITE A QUERY TO FIND ORDERS THAT ARE NOT HAPPENED IN LAST 3 MONTHS
-- OR 
-- WRITE A QUERY , JISME HUME FIND KRNA H KI .. LAST 3 MONTHS ME KON KONSE ORDERS NHI HUE H 
USE SALES ;
SHOW TABLES;

SELECT * FROM ORDERS;
SELECT *  
    FROM CUSTOMERS C LEFT JOIN ORDERS O
    ON C.CUSTOMERID = O.CUSTOMERID
    AND O.ORDERDATE >= CURRENT_DATE - INTERVAL 3 MONTH
WHERE O.ORDERID IS NULL
;

